version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/typeface
      - PORT=3000

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "4000:4000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"